### ISSUE TITLE
Comments and blank lines are lost when processed with ksflatten

### ISSUE THREAD

**Issue by Athwale** [pykickstart/pykickstart#437]
If a file begins with a comment or a blank line and is included in another ks file, the comments/lines are ignored. 

Create file test1.ks
```
%post
# File test1.ks

echo 'test 1'

# Blank line above and below.

```

Create file test2.ks
```
# File test2.ks
# Comment 2

echo 'test 2'

# Blank line above and below.

```

Create file test3.ks
```
# Comment 3
echo 'test 3'
%end
```

Create file include.ks
```
%include ./test1.ks
%include ./test2.ks
%include ./test3.ks
```

`ksflatten --config include.ks -o flat.ks`

Result:
```
# Generated by pykickstart v3.41
#version=DEVEL
# System bootloader configuration
bootloader --location=none

%post
# File test1.ks

echo 'test 1'

# Blank line above and below.

echo 'test 2'

# Blank line above and below.

echo 'test 3'
%end
```

Missing lines:
`# File test2.ks`
`# Comment 2`
`# Comment 3`

Is this by design? 
I have a massive kickstart file split into lots of smaller files which sometimes begin with comments or have commands commented and those then do not make it into the final file making it less readable.

**Comment by bcl** [comment]
Thanks for the report, I'll look into this.

**Comment by bcl** [comment]
Ends up this is working correctly. I had to remind myself since I don't usually look at the output from ksflatten :) It doesn't preserve *any* of the comment lines when flattening. It re-orders the commands (based on their write priority and then sorted by command) and writes out a completely new kickstart file. So it isn't possible to keep comments in their relevant locations in the output.
